---
# Main task file for Pi-hole setup using Ansible
- name: Combine pihole_environment_variables with inventory values take precedence
  ansible.builtin.set_fact:
    pihole_environment_variables: "{{ vars_pihole_environment_variables | default({}) | combine(pihole_environment_variables, recursive=True) }}"

- name: Debian setup tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts['distribution'] in ['Debian', 'Ubuntu']

- name: Redhat setup tasks
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_facts['distribution'] in ['Rocky', 'Red Hat Enterprise Linux']

- name: Run pre-deployment tasks
  ansible.builtin.include_tasks: pre.yml

- name: Deploy Pi-hole container
  ansible.builtin.include_tasks: deploypi.yml

- name: Configure firewall
  ansible.builtin.include_tasks: firewall.yml
  when: firewall_deploy | lower == 'true'

- name: Added Unbound
  ansible.builtin.include_tasks: unbound.yml

- name: Verify Pi-hole deployment
  ansible.builtin.include_tasks: verify.yml
