---
name: CI

"on":
  push:
    branches:
      - dev
      - master
      - "feature/**"
  pull_request:
    branches:
      - dev
      - master

env:
  python_version: 3.12

jobs:
  lint-and-syntax:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install "ansible-core>=2.16" ansible-lint yamllint

      # If you add a requirements.yml for CI deps (recommended), install it:
      - name: Install Ansible Galaxy dependencies (if present)
        run: |
          if [ -f requirements.yml ]; then
            ansible-galaxy install -r requirements.yml
          fi

      - name: YAML lint
        run: yamllint .

      - name: Ansible lint
        run: ansible-lint .

      # Syntax check is best done with a tiny test playbook that includes the role.
      - name: Ansible syntax check
        run: |
          if [ -f tests/syntax-check.yml ]; then
            ANSIBLE_ROLES_PATH="$(pwd)/..:$(pwd)" \
            ansible-playbook -i tests/inventory tests/syntax-check.yml --syntax-check
          else
            echo "No tests/syntax-check.yml found; skipping syntax-check."
          fi
